import("../../fastlane/imports/app_config_setup.rb")

default_platform(:android)

platform :android do

    lane :build_multiple_apks do
      gradle(
        task: 'assemble',
        build_type: 'dev'
      )
    end

   desc "Import Germany Package "
   lane :import_germ_package do
      setup_app_config
      sh('../../.ci_scripts/my_script.sh germ')
    end

   desc "Import Aus Package"
   lane :import_aus_package do
       setup_app_config
       sh('../../.ci_scripts/my_script.sh aus')
    end

   desc "Import USA Package"
   lane :import_usa_package do
        setup_app_config
        sh('../../.ci_scripts/my_script.sh usa')
    end
end
